ENT.Base = "base_anim"
ENT.Type = "anim"
ENT.Category 			= "Go Fish"
ENT.PrintName			= "Fishing Rod"
ENT.Author			= "G3X n' ReaperSWE"
ENT.Contact			= ""
ENT.Purpose			= "Rod"
ENT.Instructions		= ""
ENT.Spawnable			= true
ENT.AdminSpawnable		= true